# Generated by Django 5.1.6 on 2025-05-29 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='restaurant',
            new_name='restaurants',
        ),
        migrations.RenameField(
            model_name='staffrestaurant',
            old_name='restaurant',
            new_name='restaurants',
        ),
    ]
