# Generated by Django 5.2.1 on 2025-05-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_type',
            field=models.CharField(choices=[('IN', 'Indian'), ('CH', 'Chinese'), ('Th', 'Thai'), ('GR', 'Greek'), ('IT', 'Italian'), ('LB', 'Labanese')], default='', max_length=2),
            preserve_default=False,
        ),
    ]
