# Generated by Django 5.2.1 on 2025-05-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_rating_restaurant_alter_sale_restaurant_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='name',
            field=models.IntegerField(),
        ),
    ]
